### ISSUE TITLE
Just did a download and updated packages, will not build

### ISSUE THREAD

**Issue by baquick** [dotnet-presentations/blazor-workshop#93]
I am running VS 2019 Preview
Microsoft Visual Studio Community 2019 Preview
Version 16.2.0 Preview 2.0
VisualStudio.16.Preview/16.2.0-pre.2.0+29006.145
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

I did a git pull on this project.  I updated all Nuget Packages to Preview versions.  Will not compile.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseBlazor' and no accessible extension method 'UseBlazor' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	BlazingPizza.Server	C:\Blazor\Pizza\blazor-workshop\src\BlazingPizza.Server\Startup.cs	73	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseAuthorization' and no accessible extension method 'UseAuthorization' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	BlazingPizza.Server	C:\Blazor\Pizza\blazor-workshop\src\BlazingPizza.Server\Startup.cs	69	Active

I have googled and googled for a solution, but nothing.

**Comment by rynowak** [comment]
Hi @baquick - this PR just got merged to update the workshop for the latest release. https://github.com/dotnet-presentations/blazor-workshop/pull/87 - so this should be fixed now.

Note that this also requires .NET Core 3.0 preview-6 which is the current preview release.

**Comment by baquick** [comment]
Nope, this was not fixed.  After I worked thru other compile issues, that I created an issue for, I still get:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseAuthorization' and no accessible extension method 'UseAuthorization' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	BlazingPizza.Server	C:\Blazor\Pizza-Preview6\blazor-workshop\src\BlazingPizza.Server\Startup.cs	67	Active

When I decompiled the other day, the extension method for UseAuthorization was not updated to use the same builder that UseAuthentication does, and UseAuthentication works...
