### ISSUE TITLE
Pound-sign not showing up in ConfigurePizzaDialog

### ISSUE THREAD

**Issue by rynowak** [dotnet-presentations/blazor-workshop#96]
It looks like this is a compiler issue: https://github.com/aspnet/AspNetCore/issues/11225

![image](https://user-images.githubusercontent.com/1430011/59522782-60a89900-8e84-11e9-990b-59c769562081.png)

**Comment by RafaDom** [comment]
Hi rynowak - I think this is a visual studio problem (or the Blazor plugin). When creating a new item (Razor Component) the resulting encoding type of the field (filename.razor) is "ansi". I would expect to see an UTF-8 instead.  Anyways, I opened the offending file "ConfigurePizzaDialog.razor" in Notepad++, update the encoding to UTF-8 and voilá - All good now. Hope this helps.

**Comment by rynowak** [comment]
Yes, I've noticed that this isn't totally consistent, so it could be related to encodings. It's possible that the Razor Component item template is missing a BOM.

**Comment by rynowak** [comment]
We're investigating the problem as part of the VS/Razor work, but I wanted an issue here so that others could see that we're aware of it.

**Comment by danroth27** [comment]
Should be fixed now.

**Comment by ayodejii** [comment]
not fixed. I get same issue on my proj

![image](https://user-images.githubusercontent.com/43586181/164178042-74915e3c-4bca-49a4-b890-85aa697b866f.png)

**Comment by danroth27** [comment]
@ayodejii Since this is a closed issue, could you please open a new GitHub issue in the appropriate repo describing the specific problem you are hitting? If you think this is a Blazor issue, please open the issue in https://github.com/dotnet/aspnetcore/issues.
